# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SFa7DrWonDOUF757ztJ9WUqlbDfRh0A8
"""

def quick(l):
  if len(l) <=1:
    return l
  piv = l[-1]
  left = []
  right = []
  for i in l[:-1]:
    if int(i) < int(piv):
      left.append(i)
    else:
      right.append(i)
  return quick(left)+[piv]+quick(right)

l = [4,7,3,15,12,9]
print(quick(l))